{% set version = "2.5.1" %}

package:
  name: pwlf
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pwlf/pwlf-{{ version }}.tar.gz
  sha256: d60cade349682df4c1c8952e0a8761afdb1aca601718c253ae11d6add0799a6d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pydoe >=0.3.8
    - numpy >=1.14.0
    - scipy >=1.2.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - pwlf

about:
  home: https://github.com/cjekel/piecewise_linear_fit_py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'fit piecewise linear data for a specified number of line segments '

  description: |
    A library for fitting continuous piecewise linear functions to data.
    Just specify the number of line segments you desire and provide the data.
  doc_url: https://jekel.me/piecewise_linear_fit_py/
  dev_url: https://github.com/cjekel/piecewise_linear_fit_py

extra:
  recipe-maintainers:
    - cjekel
    - h-vetinari
