{% set version = "2.2.1" %}

package:
  # noarch can be enabled as soon as importlib_metada is not necessary anymore
  # noarch: python
  name: pwlf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pwlf/pwlf-{{ version }}.tar.gz
  sha256: 8133145e2541e941f09dbd0955ce9c9bca623a554ac89631ff96405e7b341b25

build:

  number: 3
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pydoe >=0.3.8
    - numpy >=1.14.0
    - scipy >=1.2.0
    - importlib-metadata  # [py<38]

test:
  imports:
    - pwlf

about:
  home: https://github.com/cjekel/piecewise_linear_fit_py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'fit piecewise linear data for a specified number of line segments '

  description: |
    A library for fitting continuous piecewise linear functions to data.
    Just specify the number of line segments you desire and provide the data.
  doc_url: https://jekel.me/piecewise_linear_fit_py/
  dev_url: https://github.com/cjekel/piecewise_linear_fit_py

extra:
  recipe-maintainers:
    - cjekel
    - h-vetinari
